Transform: AWS::Serverless-2016-10-31

Description: Deploys Python Lambdas as lambda versions to aws

Parameters:
  LambdaTimeout:
    Type: Number
    Default: 900
  Version:
    Type: String

Resources:
  ExternalDependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      LayerName: external-dependencies
      Content: ./external_dependencies

  CFAPILambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-api-lambda
      Handler: main.handler
      Runtime: python3.8
      CodeUri: ./api_lambda
      Timeout: !Ref LambdaTimeout
      Role: "{{resolve:ssm:/cf-test/cf-api-lambda-iam-role:1}}"
      Layers:
        - !Ref ExternalDependenciesLayer
      Environment:
        Variables:
          VERSION: !Ref Version
          SQS_ENDPOINT_URL: "{{resolve:ssm:/cf-test/sqs-endpoint-url:1}}"
          QUEUE_URL: "{{resolve:ssm:/cf-test/sqs-queue-url:1}}"

  CFAPILambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !GetAtt CFAPILambda.Arn
      Description: !Ref Version

  CFAPILambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !GetAtt CFAPILambda.Arn
      FunctionVersion: !GetAtt CFAPILambdaVersion.Version
      Name: !Ref Version

  CFSQSLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-sqs-lambda
      Handler: queue_processor.lambda_handler
      CodeUri: ./sqs_lambda
      Runtime: python3.8
      Timeout: !Ref LambdaTimeout
      Role: "{{resolve:ssm:/cf-test/cf-sqs-lambda-iam-role:1}}"
      Environment:
        Variables:
          VERSION: !Ref Version
          SQS_ENDPOINT_URL: "{{resolve:ssm:/cf-test/sqs-endpoint-url:1}}"
          QUEUE_URL: "{{resolve:ssm:/cf-test/sqs-queue-url:1}}"

  CFSQSLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !GetAtt CFSQSLambda.Arn
      Description: !Ref Version

  CFSQSLambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !GetAtt CFSQSLambda.Arn
      FunctionVersion: !GetAtt CFSQSLambdaVersion.Version
      Name: !Ref Version

Outputs:
  CFAPILambdaVersion:
    Description: "cf-api-lambda alias"
    Value: !Ref CFSQSLambdaAlias
    Export:
      Name: CFAPILambdaVersion
  CFSQSLambdaVersion:
    Description: "cf-sqs-lambda alias"
    Value: !Ref CFAPILambdaAlias
    Export:
      Name: CFSQSLambdaVersion
