Transform: AWS::Serverless-2016-10-31

Description: Deploys Python Lambdas as lambda versions to aws

Parameters:
  LambdaTimeout:
    Type: Number
    Default: 900
  Version:
    Type: String

Resources:
  ExternalDependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      LayerName: external-dependencies
      Content: ./external_dependencies

  CFAPILambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-api-lambda
      Handler: main.handler
      Runtime: python3.8
      CodeUri: ./api_lambda
      Timeout: !Ref LambdaTimeout
      Role: "{{resolve:ssm:/cf-test/cf-api-lambda-iam-role:1}}"
      Layers:
        - !Ref ExternalDependenciesLayer
      Environment:
        Variables:
          VERSION: !Ref Version
          SQS_ENDPOINT_URL: "{{resolve:ssm:/cf-test/sqs-endpoint-url:1}}"
          QUEUE_URL: "{{resolve:ssm:/cf-test/sqs-queue-url:1}}"

#  CFAPILambdaVersion:
#    Type: AWS::Lambda::Version
#    DeletionPolicy: Retain  # to retain existing version when underlying stack is deleted
#    UpdateReplacePolicy: Retain   # to retain existing version when deploying new version
#    Properties:
#      FunctionName: !GetAtt CFAPILambda.Arn
#      Description: !Ref Version
#
#  CFAPILambdaAlias:
#    Type: AWS::Lambda::Alias
#    DeletionPolicy: Retain  # to retain existing alias when underlying stack is deleted
#    UpdateReplacePolicy: Retain   # to retain existing alias when deploying new alias
#    Properties:
#      FunctionName: !GetAtt CFAPILambda.Arn
#      FunctionVersion: !GetAtt CFAPILambdaVersion.Version
#      Name: !Ref Version

  CFSQSLambda:
    Type: AWS::Serverless::Function
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: cf-sqs-lambda
      Handler: queue_processor.lambda_handler
      CodeUri: ./sqs_lambda
      Runtime: python3.8
      Timeout: !Ref LambdaTimeout
      Role: "{{resolve:ssm:/cf-test/cf-sqs-lambda-iam-role:1}}"
      Environment:
        Variables:
          VERSION: !Ref Version
          SQS_ENDPOINT_URL: "{{resolve:ssm:/cf-test/sqs-endpoint-url:1}}"
          QUEUE_URL: "{{resolve:ssm:/cf-test/sqs-queue-url:1}}"

  CFAPILambdaAliasDeploy:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: "{{resolve:ssm:/cf-test/publish-alias-function-arn:1}}"
      LambdaArn: !GetAtt CFAPILambda.Arn
      AliasName: !Ref Version

#  CFSQSLambdaVersion:
#    Type: AWS::Lambda::Version
#    DeletionPolicy: Retain  # to retain existing version when underlying stack is deleted
#    UpdateReplacePolicy: Retain   # to retain existing version when deploying new version
#    Properties:
#      FunctionName: !GetAtt CFSQSLambda.Arn
#      Description: cf-sqs-lambda version

#  CFSQSLambdaAlias:
#    Type: AWS::Lambda::Alias
#    DeletionPolicy: Retain  # to retain existing alias when underlying stack is deleted
#    UpdateReplacePolicy: Retain   # to retain existing alias when deploying new alias
#    Properties:
#      FunctionName: !GetAtt CFSQSLambda.Arn
#      FunctionVersion: !GetAtt CFSQSLambdaVersion.Version
#      Name: !Ref Version

#Outputs:
#  CFAPILambdaAlias:
#    Description: "cf-api-lambda alias"
#    Value: !Ref CFSQSLambdaAlias
#    Export:
#      Name: CFAPILambdaAlias
#  CFSQSLambdaAlias:
#    Description: "cf-sqs-lambda alias"
#    Value: !Ref CFAPILambdaAlias
#    Export:
#      Name: CFSQSLambdaAlias
