Transform: AWS::Serverless-2016-10-31

Resources:
  PublishAliasFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cf-lambda-alias-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: PublishVersion
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:CreateAlias
                  - lambda:PublishVersion
                Resource: '*'

  ExternalDependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      LayerName: external-dependencies
      Content: ./external_dependencies

  PublishAliasFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-publish-alias
      Description: publishes alias of a lambda
      CodeUri: ./alias_publisher
      Handler: publisher.handler
      Runtime: python3.8
      Timeout: 900
      Role: !GetAtt PublishAliasFunctionRole.Arn
      Layers:
        - !Ref ExternalDependenciesLayer

  PublishAliasFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/cf-test/publish-alias-function-arn'
      Type: String
      Description: PublishAliasFunction Arn
      Value: !GetAtt PublishAliasFunction.Arn

  CreateStageFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cf-create-stage-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CreateStage
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: '*'

  CreateStageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-create-stage
      Description: creates a new deployment and stage for an api gateway
      CodeUri: ./api_deploy
      Handler: deploy.handler
      Runtime: python3.8
      Timeout: 900
      Role: !GetAtt CreateStageFunctionRole.Arn
      Layers:
        - !Ref ExternalDependenciesLayer

  CreateStageFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/cf-test/create-stage-function-arn'
      Type: String
      Description: CreateStage function Arn
      Value: !GetAtt CreateStageFunction.Arn

  SwitchAndCleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-switch-domain-mapping-and-cleanup
      Description: switches domain mappings of preview and prod custom domains
      CodeUri: ./switch_routes
      Handler: switch_and_cleanup.handler
      Runtime: python3.8
      Timeout: 900
      Role: !GetAtt CreateStageFunctionRole.Arn
      Layers:
        - !Ref ExternalDependenciesLayer

  SwitchAndCleanupFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/cf-test/cf-switch-domain-mapping-and-cleanup-function-arn'
      Type: String
      Description: cf-switch-domain-mapping-and-cleanup function Arn
      Value: !GetAtt SwitchAndCleanupFunction.Arn